### ISSUE TITLE
County and state abbreviation in County field

### ISSUE THREAD

**Issue by shinokada** [fitnr/addfips#5]
I have [data](https://data.cdc.gov/NCHS/U-S-Life-Expectancy-at-Birth-by-State-and-Census-T/5h56-n989/data) and under County column, it has county name and state abbreviation as you can see in the image below.

![image](https://user-images.githubusercontent.com/147320/84897712-0c607680-b0e1-11ea-81ad-bd772303983e.png)

I tried the following but it didn't work.

```
import requests
import pandas as pd

url = "https://data.cdc.gov/resource/5h56-n989.json"
df = pd.read_json(url)
print(df)  # this works
df.dropna(inplace = True) 

new = df["county_name"].str.split(", ", n = 1, expand = True) 
  
# making separate first name column from new data frame 
df["county"]= new[0] 
  
# making separate last name column from new data frame 
df["abbreviation"]= new[1] 
  
# Dropping old Name columns 
df.drop(columns =["county_name"], inplace = True) 
display(df) # this works

import addfips
af = addfips.AddFIPS()
af.add_county_fips(df, county_field="county", state_field="state_name")
display(df) # this doesn't  work
```

What can you suggest?

**Comment by fitnr** [comment]
`add_county_fips` takes a dictionary, not a pandas data frame, as an argument.
