### ISSUE TITLE
Release addfips v0.4.0 on PyPI

### ISSUE THREAD

**Issue by zaneselvans** [fitnr/addfips#6]
Would y'all be willing to release the most recent version of addfips on PyPI? Currently it's [showing 0.3.1](https://pypi.org/project/addfips/) as the most recent version, but I see there's a v0.4.0 on here.

**Comment by fitnr** [comment]
Done. Thanks for the bump, it should have been automatic, but github actions 😵‍💫

**Comment by zaneselvans** [comment]
Thanks for creating and maintaining the package!

**Comment by zaneselvans** [comment]
Maybe you already noticed this, but I think the release workflow might need to be manually re-run to push out 0.4.1.

**Comment by fitnr** [comment]
The version I manually pushed to Pypi is actually 0.4.1, I just didn't bump the version in pyproject.
